Add "migration.h" to vl.c so that migrate_incoming is defined
The following patch fixes :

  qemu/vl.c:9450: warning: implicit declaration of function `migrate_incoming'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>