fix monitor.c build breakage
qemu-0.11.50 build breaks with

CC    x86_64-softmmu/monitor.o
cc1: warnings being treated as errors
/other/srcs/qemu-kvm/monitor.c: In function 'print_cpu_iter':
/other/srcs/qemu-kvm/monitor.c:450: error: format '%ld' expects type 'long
int', but argument 3 has type 'int64_t'
make[3]: *** [monitor.o] Error 1

Changes to print_cpu_iter was introduced by

commit 00ee594280d46290629ccd5fcd1b5c1a21605e4c
Author: Marcelo Tosatti <mtosatti@redhat.com>
Date:   Wed Oct 14 19:21:10 2009 -0300

    Add missing thread_id field in "info cpus"

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
--
 monitor.c |    3 ++-
 1 files changed, 2 insertions(+), 1 deletions(-)
Signed-off-by: Marcelo Tosatti <mtosatti@redhat.com>