Fix build with DEBUG_MEMREG defined
If DEBUG_MEMREG is defined, build fails as follows.

  CC    x86_64-softmmu/kvm-all.o
cc1: warnings being treated as errors
In file included from kvm-all.c:1094:
qemu-kvm.c: In function 'set_gsi':
qemu-kvm.c:127: error: too few arguments for format
qemu-kvm.c: In function 'clear_gsi':
qemu-kvm.c:137: error: too few arguments for format
qemu-kvm.c: In function 'kvm_register_phys_mem':
qemu-kvm.c:577: error: format '%lx' expects type 'long unsigned int', but argument 9 has type '__u32'
qemu-kvm.c: In function 'kvm_unregister_memory_area':
qemu-kvm.c:641: error: format '%llx' expects type 'long long unsigned int', but argument 5 has type 'uint64_t'
make[1]: *** [kvm-all.o] Error 1
make: *** [subdir-x86_64-softmmu] Error 2

Signed-off-by: Kusanagi Kouichi <slash@ac.auone-net.jp>
Signed-off-by: Avi Kivity <avi@redhat.com>