fix multiple definition of mulu64 and muls64 with user targets
After adding dummy kvm_save_mpstate change from git I would compile all
softmmu targets as expected. Although I found another problem. I cannot
compile some `user' targets.

All of them failed with:

../libuser/libuser.a(host-utils.o): In function `mulu64':
/home/users/build/rpmbuild/BUILD/qemu-kvm-0.12.1.1/host-utils.c:77: multiple definition of `mulu64'
host-utils.o:/home/users/build/rpmbuild/BUILD/qemu-kvm-0.12.1.1/host-utils.c:77: first defined here
../libuser/libuser.a(host-utils.o): In function `muls64':
/home/users/build/rpmbuild/BUILD/qemu-kvm-0.12.1.1/host-utils.c:87: multiple definition of `muls64'
host-utils.o:/home/users/build/rpmbuild/BUILD/qemu-kvm-0.12.1.1/host-utils.c:87: first defined here

Signed-off-by: Marcelo Tosatti <mtosatti@redhat.com>