Add missing declaration for qemu_system_reset
The following patch fixes :

  qemu/qemu-kvm.c:349: warning: implicit declaration of function `qemu_system_reset'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>