Fix --disable-kvm build regression due to mp_state
qemu-kvm --disable-kvm build regression of commit 8c7d4cb spotted by
qemu-kvm buildbot:

/var/lib/buildbot/qemu-kvm/disable_kvm_i386_debian_5_0/build/qemu-kvm.h: In function 'kvm_arch_get_registers':
/var/lib/buildbot/qemu-kvm/disable_kvm_i386_debian_5_0/build/qemu-kvm.h:1160: error: 'KVM_MP_STATE_HALTED' undeclared (first use in this function)
/var/lib/buildbot/qemu-kvm/disable_kvm_i386_debian_5_0/build/qemu-kvm.h:1160: error: (Each undeclared identifier is reported only once
/var/lib/buildbot/qemu-kvm/disable_kvm_i386_debian_5_0/build/qemu-kvm.h:1160: error: for each function it appears in.)
make[1]: *** [vl.o] Error 1

Signed-off-by: Daniel Gollub <gollub@b1-systems.de>
Signed-off-by: Avi Kivity <avi@redhat.com>