Re-add missing declarations for qemu_get_launch_info
The following patch re applies the declarations added to qemu/vl.h in
4213cbcf86847c8568d0147bd055d6a13bb1c963 and which were missed in merge
f4b21ce8084fc3ffcfc1a2b92bd26466700d3d40, resulting in the following
compilation warning :

  qemu/migration.c:603: warning: implicit declaration of function `qemu_get_launch_info'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>